ECOMMERCE/urls.py
from django.contrib import admin
from django.urls import path, include

# Para el manejo de archivos
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('sitio.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitio/urls.py
from django.db import router
from django.urls import path, include
from . import views
from rest_framework import routers

#Serializers
router = routers.DefaultRouter()
router.register(r'productos', views.ProductoViewSet)
router.register(r'categorias', views.CategoriaViewSet)

app_name = "SITIO"
urlpatterns = [
    # REGISTRAR USUARIO
    path('registrarse/', views.register, name="register"),


    # Paginas
    path('acercaDe', views.acerca_de, name="acerca_de"),
    path('simple_checkout', views.simple_checkout, name="simple_checkout"),
    
    # PRODUCTOS
    path('', views.producto_index, name="producto_index"),
    path('producto/agregar', views.producto_create, name="producto_create" ),
    path('producto/<int:producto_id>', views.producto_show, name="producto_show" ),
    path('producto/<int:producto_id>/editar', views.producto_edit, name="producto_edit" ),
    path('producto/<int:producto_id>/eliminar', views.producto_delete, name="producto_delete" ),
    path('producto/buscador', views.producto_search, name="producto_search"),
    path('categoria/<int:categoria_id>/productos', views.productos_por_categoria, name="productos_por_categoria"),

    # CARRITO
    path('carrito', views.carrito_index, name="carrito_index"),
    path('carrito/agregar', views.carrito_save, name="carrito_save"),
    path('carrito/clean', views.carrito_clean, name="carrito_clean"),
    path('item_carrito/<int:item_carrito_id>/eliminar', views.item_carrito_delete, name="item_carrito_delete"),

    #Simple checkout
    #path('', views.simple_checkout, name="simple_checkout"),
    path('complete/', views.paymentComplete, name="complete"),

    #Serializer
    path('api/', include(router.urls)),
]

sitio/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import Textarea

# Create your models here.
class Categoria(models.Model):
    descripcion = models.CharField(max_length=200, null=False)

    def __str__(self):
        return self.descripcion


class Producto(models.Model):
    titulo = models.CharField(max_length=100, null=False)
    # Imagen
    imagen = models.FileField(upload_to='imagenes/productos/')
    descripcion = models.TextField(null=False, blank=False)
    marca = models.CharField(max_length=50, null=False, default='')
    color = models.CharField(max_length=50, null=False, default='')
    precio = models.IntegerField(null=False, default=0)
    codigo = models.CharField(max_length=50, null=False, default='')
    stock = models.IntegerField(null=False, default=0)
    # FK
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE, related_name="productos")

    def __str__(self):
        return self.titulo

class Order(models.Model):
    ordernum = models.CharField(max_length=9, null=True, blank=True)
    customer = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.ordernum

class Order_Detail(models.Model):
    product = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cant = models.IntegerField(default=1)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.product.titulo

class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="carrito")
    total = models.DecimalField(null=False, max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return f"Id: {self.pk} | Usuario_id: {self.usuario.id} | Usuario: {self.usuario.username} | Total: {self.total}"


class Carrito_item(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, related_name="items")

    def __str__(self) -> str:
        return f"Id: {self.pk} | Producto: {self.producto.titulo} | Carrito_id: {self.carrito.id}"

sitio/forms.py
from django import forms
from django.db.models import fields
from .models import Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

""" 
    PRODUCTO 
"""
class FormProducto(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ('titulo','imagen','descripcion', 'marca', 'color', 'stock', 'precio', 'codigo', 'categoria')
        """ widgets = {
            'titulo': forms.TextInput(),
            'descripcion' : forms.Textarea(),
            'marca' : forms.TextInput(),
            'color' : forms.TextInput(),
            'stock': forms.NumberInput(),
            'precio' : forms.NumberInput(),
            'codigo' : forms.TextInput(),
            'imagen' : forms.FileField()
        } """
        """ widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingrese el nombre del producto...' , 'required': True}),
            'descripcion' : forms.Textarea(attrs={'class' : 'form-control', 'row' : 3, 'required': True}),
            'marca' : forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingrese la marca del producto...' , 'required': True}),
            'color' : forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingrese el color del producto...' , 'required': True}),
            'stock': forms.NumberInput(attrs={'class': 'form-control', 'placeholder':'Ingrese el stock del producto...' , 'required': True}),
            'precio' : forms.NumberInput(attrs={'class' : 'form-control', 'placeholder':'XXXX', 'required': True}),
            'codigo' : forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingrese el codigo del producto...' , 'required': True}),
            'imagen' : forms.FileField(attrs={'class':'form-control-file', 'id':'imagen', 'placeholder': 'Ingrese la imagen...', 'required': True})
        } """

sitio/views.py
import json
from random import random
from django.contrib.auth.models import User
from sitio.forms import FormProducto
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponse
from sitio.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from rest_framework import viewsets
from .serializers import ProductoSerializer, CategoriaSerializer

#SERIALIZERS
class ProductoViewSet(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer

class CategoriaViewSet(viewsets.ModelViewSet):
    queryset = Categoria.objects.all()
    serializer_class = CategoriaSerializer


""" 
    REGISTRO DE USUARIO
"""
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            usuario_logeado = User.objects.last()
            #username = form.cleaned_data['username']
            messages.success(request, f"El usuario ha sido registrado exitosamente!")
            carrito = Carrito()
            carrito.usuario = usuario_logeado
            carrito.total = 0
            carrito.save()
            return redirect('SITIO:producto_index')
        else:
            messages.success(request, "No se pudo registrar el usuario, vuelva a intenarlo!")

    return render(request, 'sitio/register.html')

""" 
    PRODUCTOS
"""
def producto_index(request):
    productos = Producto.objects.all().order_by("-id")
    
    return render(request, "sitio/producto/index.html", {
        'categorias' : Categoria.objects.all(),
        'productos_top3' : productos[:3],
        'productos' : productos[3:10]
    })

# PARA ADMINS/MODERADORES
def producto_create(request):
    categorias = Categoria.objects.all()
    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(id=request.POST["categoria"])
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            form.save()
            return redirect("SITIO:producto_index")
            #return HttpResponse('Los campos fueron validados y aceptados!!! ' + str(categoria_del_producto))
        else:
            return render(request, 'sitio/producto/create.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'sitio/producto/create.html', {
            'categorias' : categorias
        })

def producto_show(request, producto_id):
    producto =  get_object_or_404(Producto, id=producto_id)

    return render(request, 'sitio/producto/show.html',{
        'categorias' : Categoria.objects.all(),
        'producto' : producto
    })

def producto_edit(request, producto_id):
    categorias = Categoria.objects.all()
    producto = Producto.objects.get(id=producto_id)

    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(id=request.POST["categoria"])
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            producto.titulo = request.POST['titulo']
            producto.categoria = categoria_del_producto
            producto.descripcion = request.POST['descripcion']
            producto.stock = request.POST['stock']
            producto.imagen = request.FILES['imagen']
            producto.precio = request.POST['precio']
            producto.save()
            return redirect("SITIO:producto_index")
        else:
            return render(request, 'sitio/producto/edit.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'sitio/producto/edit.html',{
            'categorias' : categorias,
            'producto' : producto
        })

def producto_delete(request, producto_id):
    producto = Producto.objects.get(id=producto_id)
    producto.delete()
    return redirect('SITIO:producto_index')
    #return HttpResponse(f'Eliminar producto_id: {producto.id}')

def producto_search(request):
    request.session["paypal"] = True
    texto_de_busqueda = request.GET["texto"]
    productosPorTitulo = Producto.objects.filter(titulo__icontains = texto_de_busqueda).all()
    productosPorDescripcion = Producto.objects.filter(descripcion__icontains = texto_de_busqueda).all()
    productos = productosPorTitulo | productosPorDescripcion
    return render(request, 'sitio/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos,
        'texto_buscado' : texto_de_busqueda,
        'titulo_seccion' : 'Productos que contienen',
        'sin_productos' : 'No hay producto de la categoria ' + texto_de_busqueda
    })

def productos_por_categoria(request, categoria_id):
    
    #categoria = Categoria.objects.get(id=categoria_id)
    categoria = get_object_or_404(Categoria, id = categoria_id)
    productos = categoria.productos.all()
    return render(request, 'sitio/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos,
        'categoria' : categoria.descripcion,
        'titulo_seccion' : 'Productos de la categoria',
        'sin_productos' : 'No hay producto de la categoria ' + categoria.descripcion
    })

""" 
    CARRITO
"""
def carrito_index(request):
    request.session["paypal"] = False
    categorias = Categoria.objects.all()
    usuario_logeado = User.objects.get(username=request.user)
    productos = Carrito.objects.get(usuario=usuario_logeado.id).items.all()

    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    nuevo_precio_Carrito = 0
    for item in carrito.items.all():
        nuevo_precio_Carrito += item.producto.precio
    carrito.total = nuevo_precio_Carrito
    carrito.save()

    return render(request, 'sitio/carrito/index.html', {
        'categorias' : categorias,
        'usuario' : usuario_logeado,
        'items_carrito' : productos
    })

def carrito_save(request):
    #tieneCarrito = Carrito.objects.filter(usuario=8).count()
    # Devuelve un 404 si no encuentra el carrito
    #arrito = get_object_or_404(Carrito, usuario=usuario_logeado.id)

    if request.method == 'POST':
        producto = Producto.objects.get(id=request.POST['producto_id'])
        usuario_logeado = User.objects.get(username=request.user)

        # Agrego producto al carrito
        carrito = Carrito.objects.get(usuario=usuario_logeado.id)
        item_carrito = Carrito_item()
        item_carrito.carrito = carrito
        item_carrito.producto = producto
        item_carrito.save()

        # Sumo el precio del producto al carrito
        carrito.total = producto.precio + carrito.total
        carrito.save()
        messages.success(request, f"El producto {producto.titulo} fue agregado al carrito")
        #return HttpResponse(f"{usuario_logeado.id} | ITEM_CARRITO: {item_carrito} | CARRITO: {carrito}")
        return redirect("SITIO:producto_index")

    else:
        return redirect("SITIO:producto_index")

def carrito_clean(request):
    usuario_logeado = User.objects.get(username=request.user)
    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    carrito.items.all().delete()
    carrito.total = 0
    carrito.save()
    #return HttpResponse(f'Carrito: id({carrito.id}) ${carrito.total} | Usuario: id({usuario_logeado.id}) {usuario_logeado.username} | items_carrito: {carrito.items.all().count()}')
    return redirect('SITIO:carrito_index')

def item_carrito_delete(request, item_carrito_id):
    item_carrito = Carrito_item.objects.get(id=item_carrito_id)
    carrito = item_carrito.carrito
    
    # Vuelvo a calcular el precio del carrito
    nuevo_precio_Carrito = 0 - item_carrito.producto.precio
    for item in carrito.items.all():
        nuevo_precio_Carrito += item.producto.precio

    # Realizo los cambios en la base de datos
    carrito.total = nuevo_precio_Carrito
    item_carrito.delete()
    carrito.save()
    return redirect("SITIO:carrito_index")
    #return HttpResponse(f'Carrito_id: {carrito.id} Total: {carrito.total} | Item_carrito: {item_carrito} | Precio: {precio_item}')

"""
    PAGINAS
"""
def acerca_de(request):
    return render(request, 'sitio/paginas/acerca_de.html',{
        'categorias' : Categoria.objects.all(),
    })

def simple_checkout(request):
    return render(request, 'sitio/carrito/simple_checkout.html')

def paymentComplete(request):
    body = json.loads(request.body)
    sess = request.session.get("data",{"items":[]})
    productos_carro = sess["items"]
    #datos cabecera
    Oc = Order()
    Oc.customer = body['customer']
    Oc.ordernumber = random.randint(10000,99999)
    Oc.save()
    for item in productos_carro:
        prod = Producto.objects.get(slug=item)
        Od = Order_Detail()
        Od.product = prod
        Od.cant = 1
        Od.order = Oc
        Od.save()
    del request.session["data"]
    return redirect("sitio:sucess")

def sucess(request):
    productos = Producto.objects.filter(activo = True)
    categorias = Categoria.objects.all(activo = True)
    context = {"productos":productos, "categorias":categorias}
    return render(request, 'sitio/carrito/sucess.html', context)

sitio/templates/sitio/carrito/index.html
{% extends "sitio/layout.html" %}

{% block content %}
<main class="container my-5">
    <div class="row justify-content-center">

        <!-- TITULO -->
        <div class="col-12 mb-3">
            <h2 class="display-4 text-center text-capitalize">carrito</h2>
        </div>

        <div class="col-6 row border">

            <!-- USUARIO -->
            <div class="col-12 p-0 mb-2">
                <h3 class="display-4 text-capitalize mt-2" style="font-size: 2em;">{{usuario.username.capitalize}}</h3>
            </div>

            <!-- PRODUCTOS -->
            {% for item in items_carrito %}
                <div class="col-12 p-0 m-0">
                    <p class="d-flex justify-content-between align-items-center">
                        {{ forloop.counter }}. {{item.producto.titulo.title}} - ${{ item.producto.precio }}
                        <a href="{% url 'SITIO:item_carrito_delete' item.id %}">X</a>
                    </p>
                </div>
            {% empty %}
                <div class="col-12 p-0 m-0">
                    <p class="d-flex justify-content-between align-items-center">
                        No tiene ningun producto en el carrito
                    </p>
                </div>
            {% endfor %}

            <!-- BOTONES -->
            <div class="col-12 p-0 m-0 my-3 row ">
                <div class="col-md-5 col-lg-3 p-0">
                    <a href="{% url 'SITIO:carrito_clean' %}" class="btn btn-danger btn-block">Vaciar Carrito</a>
                </div>
                <div class="col-12 p-0 col-md-7 col-lg-4 mt-2 mt-md-0 pl-md-3">
                    <button class="btn btn-success btn-block"><a href="{% url 'SITIO:simple_checkout' %}" style="color: white ;">Pagar</a></button>
                </div>

            </div>
        </div>

    </div>
</main>
{% endblock %}

sitio/templates/sitio/carrito/simple_checkout.html
<!DOCTYPE html>
<html>

<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <div class="col-12 col-sm-6 col-md-4 mb-3">
    <div style="position: relative; top: 200px; left: 500px;">
      <script
        src="https://www.paypal.com/sdk/js?client-id=AR2I9NMrxqlJdtxO_mnkPibTl-S-H9ROL55vLNBOD2kiqV7V7qp9bDN18nCO8oG3B3b2j7deYY1g0ckA&currency=USD">
      </script>
      <!-- Set up a container element for the button -->
      <div id="paypal-button-container"></div>
      <script>
        paypal.Buttons({
          // Sets up the transaction when a payment button is clicked
          createOrder: (data, actions) => {
            return actions.order.create({
              purchase_units: [{
                amount: {
                  value: '238960.41' // Can also reference a variable or function
                }
              }]
            });
          },
          // Finalize the transaction after payer approval
          onApprove: (data, actions) => {
            return actions.order.capture().then(function (orderData) {
              // Successful capture! For dev/demo purposes:
              console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
              const transaction = orderData.purchase_units[0].payments.captures[0];
              alert(
                `Transaction ${transaction.status}: ${transaction.id}\n\nSee console for all available details`
              );
              // When ready to go live, remove the alert and show a success message within this page. For example:
              // const element = document.getElementById('paypal-button-container');
              // element.innerHTML = '<h3>Thank you for your payment!</h3>';
              // Or go to another URL:  actions.redirect('thank_you.html');
            });
          }
        }).render('#paypal-button-container');
      </script>
    <!-- Replace "test" with your own sandbox Business account app client ID -->
    <script
      src="https://www.paypal.com/sdk/js?client-id=AR2I9NMrxqlJdtxO_mnkPibTl-S-H9ROL55vLNBOD2kiqV7V7qp9bDN18nCO8oG3B3b2j7deYY1g0ckA&currency=USD">
    </script>
    <!-- Set up a container element for the button -->
    <div id="paypal-button-container"></div>
    <script>
      paypal.Buttons({
        // Sets up the transaction when a payment button is clicked
        createOrder: (data, actions) => {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: '238960.41' // Can also reference a variable or function
              }
            }]
          });
        },
        // Finalize the transaction after payer approval
        onApprove: (data, actions) => {
          return actions.order.capture().then(function (orderData) {
            // Successful capture! For dev/demo purposes:
            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
            const transaction = orderData.purchase_units[0].payments.captures[0];
            alert(
              `Transaction ${transaction.status}: ${transaction.id}\n\nSee console for all available details`
              );
            // When ready to go live, remove the alert and show a success message within this page. For example:
            // const element = document.getElementById('paypal-button-container');
            // element.innerHTML = '<h3>Thank you for your payment!</h3>';
            // Or go to another URL:  actions.redirect('thank_you.html');
          });
        }
      }).render('#paypal-button-container');
    </script>
    <a href="/" class="btn btn-primary btn-lg" tabindex="-1" role="button" aria="true">Volver al Home</a>
  </div>
</div>

<div>
  
</div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>
</body>

</html>

sitio/templates/sitio/carrito/sucess.html
{% load static %}
{% extends "sitio/layout.html" %}

<body>
    <div>
        <h3>Gracias por tu compra!!</h3>
        <p>¡No te pierdas las mejores ofertas!</p>
        <p>¡Te esperamos en nuestra tienda!</p>
        <a href="{% url 'sitio:producto_index' %}"></a>
    </div>
</body>